
package de.htwg_konstanz.ebus.ess.ws.delivery;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryService", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/delivery", wsdlLocation = "file:/C:/Users/Steph/eclipse-workspace/EBUT/Assignment3/WholesalerWebDemo/WebContent/wsdl/DeliveryService.wsdl")
public class DeliveryService
    extends Service
{

    private final static URL DELIVERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYSERVICE_EXCEPTION;
    private final static QName DELIVERYSERVICE_QNAME = new QName("http://www.htwg-konstanz.de/ebsf/ws/delivery", "DeliveryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Steph/eclipse-workspace/EBUT/Assignment3/WholesalerWebDemo/WebContent/wsdl/DeliveryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYSERVICE_WSDL_LOCATION = url;
        DELIVERYSERVICE_EXCEPTION = e;
    }

    public DeliveryService() {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME);
    }

    public DeliveryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME);
    }

    public DeliveryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYSERVICE_QNAME, features);
    }

    public DeliveryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryServicePortType
     */
    @WebEndpoint(name = "DeliveryServicePort")
    public DeliveryServicePortType getDeliveryServicePort() {
        return super.getPort(new QName("http://www.htwg-konstanz.de/ebsf/ws/delivery", "DeliveryServicePort"), DeliveryServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryServicePortType
     */
    @WebEndpoint(name = "DeliveryServicePort")
    public DeliveryServicePortType getDeliveryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.htwg-konstanz.de/ebsf/ws/delivery", "DeliveryServicePort"), DeliveryServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYSERVICE_EXCEPTION!= null) {
            throw DELIVERYSERVICE_EXCEPTION;
        }
        return DELIVERYSERVICE_WSDL_LOCATION;
    }

}
