
package de.htwg_konstanz.ebus.ess.ws.delivery;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeliveryServicePortType", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/delivery")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeliveryServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns de.htwg_konstanz.ebus.ess.ws.delivery.DeliveryServiceResponse
     * @throws DeliveryServiceFault
     */
    @WebMethod
    @WebResult(name = "DeliveryServiceResponse", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/delivery", partName = "response")
    public DeliveryServiceResponse handleOrderDelivery(
        @WebParam(name = "DeliveryServiceRequest", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/delivery", partName = "request")
        DeliveryServiceRequest request)
        throws DeliveryServiceFault
    ;

}
