
package de.htwg_konstanz.ebus.ess.ws.order;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServicePortType", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/order")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns de.htwg_konstanz.ebus.ess.ws.order.OrderServiceResponse
     * @throws OrderServiceFault
     */
    @WebMethod
    @WebResult(name = "OrderServiceResponse", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/order", partName = "response")
    public OrderServiceResponse purchaseOrder(
        @WebParam(name = "OrderServiceRequest", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/order", partName = "request")
        OrderServiceRequest request)
        throws OrderServiceFault
    ;

}
