
package de.htwg_konstanz.ebus.ess.ws.invoice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoiceServicePortType", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/invoice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InvoiceServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns de.htwg_konstanz.ebus.ess.ws.invoice.InvoiceServiceResponse
     * @throws InvoiceServiceFault
     */
    @WebMethod
    @WebResult(name = "InvoiceServiceResponse", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/invoice", partName = "response")
    public InvoiceServiceResponse handleOrderInvoice(
        @WebParam(name = "InvoiceServiceRequest", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/invoice", partName = "request")
        InvoiceServiceRequest request)
        throws InvoiceServiceFault
    ;

}
