
package de.htwg_konstanz.ebus.ess.ws.invoice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InvoiceService", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/invoice", wsdlLocation = "file:/C:/Users/Steph/eclipse-workspace/EBUT/Assignment3/WholesalerWebDemo/WebContent/wsdl/InvoiceService.wsdl")
public class InvoiceService
    extends Service
{

    private final static URL INVOICESERVICE_WSDL_LOCATION;
    private final static WebServiceException INVOICESERVICE_EXCEPTION;
    private final static QName INVOICESERVICE_QNAME = new QName("http://www.htwg-konstanz.de/ebsf/ws/invoice", "InvoiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Steph/eclipse-workspace/EBUT/Assignment3/WholesalerWebDemo/WebContent/wsdl/InvoiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVOICESERVICE_WSDL_LOCATION = url;
        INVOICESERVICE_EXCEPTION = e;
    }

    public InvoiceService() {
        super(__getWsdlLocation(), INVOICESERVICE_QNAME);
    }

    public InvoiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVOICESERVICE_QNAME, features);
    }

    public InvoiceService(URL wsdlLocation) {
        super(wsdlLocation, INVOICESERVICE_QNAME);
    }

    public InvoiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVOICESERVICE_QNAME, features);
    }

    public InvoiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InvoiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvoiceServicePortType
     */
    @WebEndpoint(name = "InvoiceServicePort")
    public InvoiceServicePortType getInvoiceServicePort() {
        return super.getPort(new QName("http://www.htwg-konstanz.de/ebsf/ws/invoice", "InvoiceServicePort"), InvoiceServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvoiceServicePortType
     */
    @WebEndpoint(name = "InvoiceServicePort")
    public InvoiceServicePortType getInvoiceServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.htwg-konstanz.de/ebsf/ws/invoice", "InvoiceServicePort"), InvoiceServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVOICESERVICE_EXCEPTION!= null) {
            throw INVOICESERVICE_EXCEPTION;
        }
        return INVOICESERVICE_WSDL_LOCATION;
    }

}
